njustesen/botbowl

README.md, ffai/ai/env.py
Found one more small typo. It looks like the key `own apothecary available` was repeated twice instead of making the second one `opp apothecary available`.
=> Opp apothecary available

ffai/core/model.py
I think there is a typo, it should be 3 block dice when the strength is more than double of opponent.
=> 3 block dice if more than double strength of opponent

examples/multi_gym_example.py
The outer for statement does not end because the nested for statement used the same variable `i`. Modified inner iterator variable to `j`.
=> Fix variable name (nested for loop has same variable)

ffai/core/model.py
`p` was duplicated twice. It seems that `c` should be entered.
=> fixed typo

ffai/core/table.py
correcting dupes in skills list - fixes orc troll error
=> small skills enum fix

ffai/ai/__init__.py, ffai/ai/registry.py, ffai/core/load.py, ffai/data/config/ff-1.json, ffai/data/config/ff-11-bot-bowl-i.json, ffai/data/config/ff-11-web.json, ffai/data/config/ff-11.json, ffai/data/config/ff-3.json, ffai/data/config/ff-5.json, ffai/data/config/ff-7.json, ffai/web/api.py, ffai/web/package-lock.json, ffai/web/server.py, ffai/web/static/dist/js/pybowl.js, ffai/web/static/js/controllers.js, ffai/web/static/js/services.js, ffai/web/static/partials/game.create.html
This fixes the create game page, and adds an option to choose human or bot as coach
=> Creategame page fix

ffai/core/procedure.py
corrects the sidestep target squares to be all empty adjacent
reports use of sidestep
=> Sidestep fix

ffai/core/procedure.py
inc. small tweak to pass blitz flag into Block()
=> reporting horns skill use on blitz

ffai/core/procedure.py
Adds Nerves of steel on Pass and Catch/Intercept
fixes issue #62
I mean, I'm not a fan of elves, but it seemed like an easier fix than bone-head
=> Add Nerves of steel skill

ffai/core/procedure.py
=> stunty applies -1 pass modifier

tests/test_injury.py
A couple of tests for thick skull 
Current implement is correct,  therefore can close issue #57
=> add tests for thick skull

ffai/core/game.py, ffai/core/procedure.py, ffai/core/table.py, ffai/web/static/dist/js/pybowl.js, ffai/web/static/js/services.js, tests/game/test_casualty.py
added code for skill on casualty. moved to game as shared between Casualty and Apothecary procedures.
=> Regeneration skill + test

ffai/core/game.py, ffai/web/host.py, ffai/web/server.py
Fixing issue #87 
part 1: A bug with absolute file paths.
part 2: pause clocks on save, then restart clocks on resume.
I have added a clock.resume to the check_clocks method. Not 100% sure if this will cause any side effects?
=> Save game / resume fixes

ffai/web/static/dist/css/style.css, ffai/web/static/less/style.less
small fix to scrollbar issue on chrome/windows
removed overflow attribute
=> skill-box scrollbar fix

ffai/web/static/partials/game.create.html
fix after split into separate lists
=> Correcting the create-game skill list in roster table

docs/features.md, docs/gym.md, ffai/core/procedure.py, tests/game/test_pass.py
Smallest little thing.. But my first contribution to the project and I finally think I understand git :)
=> Fixed Pass skill re-roll and typo in tutorial

docs/features.md, ffai/core/procedure.py, tests/game/test_pass.py
Something went wrong with the previous pull request. Here it is again!
=> Pass skill reroll - fixes issue #111

ffai/ai/layers.py, tests/performance/run_env.py
1) An abstract class "MemoizedFeatureLayer" to speed up generating certain layers. 
2) Some optimized layer generation methods
3) Small test for the profiler. 
20% speed increase in the profiler test on my laptop! 
possibly need to add cProfile as a package to the requirements now.
=> Performance increase in layers.py

docs/features.md, ffai/core/game.py, ffai/core/procedure.py, ffai/core/table.py, tests/game/test_strip_ball.py, tests/game/test_timber.py
I took the conservative decision and named it "TIMBER" in the code.
=> Strip Ball and TIMMM-BER! 

ffai/ai/pathfinding.py, ffai/core/procedure.py, tests/ai/test_pathfinding.py
=> Pathfinding does not stop pre-maturely if no moves are left

ffai/core/load.py
The parsing of the formation file can be done more pythonic and safer by using a context manager and explicitly converting the line into a list.
=> Refactor parsing formation file

ffai/core/game.py, setup.py, tests/framework/test_forward_model.py
game.actor should now be properly reset after calling game.revert()
=> Forward model bugfix - game.actor not properly reset

botbowl/core/forward_model.py, botbowl/core/game.py, botbowl/core/model.py, botbowl/core/pathfinding/cython_pathfinding.pyx, botbowl/core/pathfinding/python_pathfinding.py, botbowl/core/procedure.py, botbowl/core/util.py
Starts work with #183 . 
solves a small bug with how python pathfinding interacts with the forward model. 
Adds __repr__() for some of the models.
=> Annotations

.github/workflows/pythonpackage.yml
=> Python 3.10 added to github workflow

botbowl/ai/proc_bot.py, botbowl/core/procedure.py, docs/bots-ii.md, examples/scripted_bot_example.py, tests/ai/test_scripted_bot.py
Fixes bugs raised by user "carlosto" on Discord (@ctelloordonez on github). 
1. Introduces function `path_to_move_actions(game, path) -> List[Action]` which converts a Path returned from the pathfinding algorithms to actions, including blitz, handoff and foul. It makes the code more readable and makes the bot agnostic to whether the current game has pathfinding enabled or not. 
2. Solves bug with None being returned by `MyScriptedBot.setup()`. Solution found by _carlosto_. 
3. Introduces test for scripted bot, the simply runs a game between two scripted bots.
=> Fixes bugs in MyScriptedBot

botbowl/core/forward_model.py, botbowl/core/game.py, botbowl/core/model.py, botbowl/core/pathfinding/cython_pathfinding.pyx, botbowl/core/pathfinding/python_pathfinding.py, botbowl/core/procedure.py, botbowl/core/util.py, tests/framework/test_forward_model.py, tests/game/test_dodge.py, tests/game/test_negatraits.py, tests/performance/benchmark_forward_model.py, tests/util.py
This PR should be considered after PRs #191 and #190 have been merged (they have been merged now). This branch is built on top of those changes. 
This PR contains: 
1. Feature to step the game state forward after being reverted. 
2. New ways to set classes in `models.py` to immutable using decorators instead of inheritence which speeds up execution and readability. 
3. Some general optimizations of forward_model.py, game.py, procedures.py, pathfinding.py
=> Forward model update and optimizations

botbowl/core/game.py, botbowl/web/api.py, botbowl/web/host.py, botbowl/web/server.py, botbowl/web/static/dist/js/botbowl.js, botbowl/web/static/js/controllers.js, botbowl/web/static/js/services.js, botbowl/web/static/partials/game.list.html, botbowl/web/static/partials/game.play.html
Fixes #87 by changing small things in existing code.
Some UX improvements could be made but I don't want to spend further time on it now, e.g.:
- Angular-like page updating to avoid flickering
- The table rows and buttons don't align well 
- Right now, the web page doesn't jump into the game automatically when it's loaded to allow the user to select team/hotseat but the timer starts imediately. This could be impemented when we have a pause/resume feature.
=> Saving, loading, and deleting works

botbowl/core/game.py, tests/framework/test_forced_action.py
Fixes #213 by forcing random actions (except PLACE_PLAYER) until setup is legal.
=> Fix to forced setup

examples/competition_example.py
Fixes #219 by adding `if __name__ == '__main__':`.
=> Fixes freeze_support bug on macbook pro

botbowl/ai/env.py, botbowl/data/teams/1/human.json, botbowl/data/teams/3/human.json, botbowl/data/teams/5/human.json, botbowl/data/teams/7/human.json, tests/ai/test_env.py
Fixes #223 by using the EnvCong.size property to load the correct team and renamed renamed team files from `data/<board-size>/human-<board-size>.json` to `data/<board-size>/human.json`.
Also changed teams to always have 1 reserve player.
=> Team loading bug fixed

botbowl/ai/env.py, tests/ai/test_env.py
Fixes #70 by passing the seed to the RandomBot in BotBowlEnv.
=> Adds seed to RandomBot in BotBowlEnv

setup.py
A hot fix to #245.
A proper fix should make it work in the new gym version but let's get this hotfix in first.
=> Hotfix to gym version issue 

botbowl/web/static/partials/game.play.html
The replay buttons wasn't clickable.
The crowd square bar was overlapping the replay button bar. I made a conditional to move it down if it's replaying.
=> Replay button fix

.github/workflows/pythonpackage.yml, botbowl/ai/competition/__init__.py, botbowl/ai/competition/competition.py, botbowl/ai/competition/python_socket.py, botbowl/ai/competition/result_structures.py, botbowl/ai/registry.py, botbowl/core/game.py, botbowl/core/model.py, examples/competition_example.py, examples/containerized_bot.py, requirements.txt, tests/ai/test_competition.py
Introduces two new features which will be important for running the botbowl competition: 
**DockerAgent** - A class that starts an agent in a docker container and connects to it using the features in PythonSocketClient.
**MultiAgentCompetition** - A competition that can take any number of agents, let them all play against each other and determine the winner. Also has functions to neatly display the results. 
In addition this PR also refactors major parts of `botbowl.ai.competition.*`.
=> Multi-agent competition + DockerAgent

botbowl/core/game.py, botbowl/core/model.py
Went to town on linter errors in game.py, have a brief look or just trust me and the test suite :)
=> More types and less linter errors
